// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyAMCrhOkOWB7ZzIYLTGjgJyHAeVfzd-20Y',
    appId: '1:115824667190:web:1b4596c0452457d4a90697',
    messagingSenderId: '115824667190',
    projectId: 'renttas-8eb75',
    authDomain: 'renttas-8eb75.firebaseapp.com',
    storageBucket: 'renttas-8eb75.appspot.com',
    measurementId: 'G-17TNQ46E2K',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyCO6WDfqQ3qeW9OL4ouR7LwTW67-iZCjxE',
    appId: '1:115824667190:android:fead76cce4d14d44a90697',
    messagingSenderId: '115824667190',
    projectId: 'renttas-8eb75',
    storageBucket: 'renttas-8eb75.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyAlLikkR7hjtqzuPniJdDgs3KNgVT-m7pU',
    appId: '1:115824667190:ios:10168919e60d7f9aa90697',
    messagingSenderId: '115824667190',
    projectId: 'renttas-8eb75',
    storageBucket: 'renttas-8eb75.appspot.com',
    iosBundleId: 'com.example.renttasFlutterApp',
  );

  static FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyAlLikkR7hjtqzuPniJdDgs3KNgVT-m7pU',
    appId: '1:115824667190:ios:f698172175e1c2fda90697',
    messagingSenderId: '115824667190',
    projectId: 'renttas-8eb75',
    storageBucket: 'renttas-8eb75.appspot.com',
    iosBundleId: 'com.example.renttasFlutterApp.RunnerTests',
  );
}
