// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAACrY4NCTXG3QXw5f3gPMfVXN8EyOgqGE',
    appId: '1:966686413441:web:d708e79d9b8c6543137380',
    messagingSenderId: '966686413441',
    projectId: 'renttas-main-project',
    authDomain: 'renttas-main-project.firebaseapp.com',
    storageBucket: 'renttas-main-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Ht-tmztUqz5DRaFS4lioSOI12eDFm4Q',
    appId: '1:966686413441:android:c1a5662e1b5f4c50137380',
    messagingSenderId: '966686413441',
    projectId: 'renttas-main-project',
    storageBucket: 'renttas-main-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApRpKiuspWYmU_nJkNlhH9FpUEBRZSEhk',
    appId: '1:966686413441:ios:58a6aa642292914e137380',
    messagingSenderId: '966686413441',
    projectId: 'renttas-main-project',
    storageBucket: 'renttas-main-project.appspot.com',
    iosBundleId: 'com.example.rentos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApRpKiuspWYmU_nJkNlhH9FpUEBRZSEhk',
    appId: '1:966686413441:ios:58a6aa642292914e137380',
    messagingSenderId: '966686413441',
    projectId: 'renttas-main-project',
    storageBucket: 'renttas-main-project.appspot.com',
    iosBundleId: 'com.example.rentos',
  );
}
